<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-android36.0</TargetFramework>
        <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>Tonestro.Maui.RevenueCat.Android</PackageId>
        <Version>10.14.1.1</Version>
        <Description>Contains bindings for https://docs.revenuecat.com/docs/android</Description>
        <Authors>Christian Kapplmüller, Albilaga Linggra Pradana</Authors>
        <Company>fun.music IT GmbH</Company>
        <PackageOutputPath>nugetoutput</PackageOutputPath>
        <PackageLicensePath>..\..\..\LICENSE.txt</PackageLicensePath>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedAllSources>true</EmbedAllSources>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Dev.Drewhamilton.Poko.PokoAnnotations" Version="0.18.2" />
        <PackageReference Include="Xamarin.Android.Google.BillingClient" Version="8.3.0.2" />
        <PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.10.0.1" />
        <PackageReference Include="Xamarin.AndroidX.Core.Core.Ktx" Version="1.19.0.1" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.11.0.1" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.11.0.1" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.11.0.1" />
        <PackageReference Include="Xamarin.Google.Crypto.Tink.Android" Version="1.23.0" />
        <PackageReference Include="Xamarin.GooglePlayServices.Ads.Identifier" Version="118.3.0.2" />
        <PackageReference Include="Xamarin.GooglePlayServices.Auth.Blockstore" Version="116.4.0.9" />
        <PackageReference Include="Xamarin.Kotlin.Parcelize.Runtime" Version="2.4.0.1" />
        <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk8" Version="2.4.0.1" />
        <PackageReference Include="Xamarin.KotlinX.Coroutines.Core" Version="1.11.0.1" />
        <PackageReference Include="Xamarin.KotlinX.Serialization.Core" Version="1.11.0.1" />
        <PackageReference Include="Xamarin.KotlinX.Serialization.Json" Version="1.11.0.1" />
    </ItemGroup>
    <ItemGroup>
        <AndroidLibrary Include="Jars\purchases-10.14.1.aar">
            <Bind>true</Bind>
            <Pack>true</Pack>
        </AndroidLibrary>
    </ItemGroup>
    <ItemGroup>
        <JavaSourceJar Include="Jars\purchases-10.14.1-sources.jar" />
    </ItemGroup>
</Project>
